# Week 8: Data Wrangling HW

> Laiba Siddique

## Tasks

### Task 1: Select the `Vocation` column and assign it to the variable `vocation`. Confirm that the object assigned to vocation is a pandas series object. The `tail` function (with no arguments), prints the last five observations to the screen. Use the `tail` function to print the last five observations in `vocation` to the screen.

In [10]:
vocation = df['Vocation']

In [11]:
type(vocation)

pandas.core.series.Series

In [12]:
vocation.tail()

195            Sales professional, IT
196                         Paramedic
197    Chartered certified accountant
198                            Dancer
199                Theme park manager
Name: Vocation, dtype: object

### Task 2: Print the `TAG` and the `Smoke` variables to the screen, but only for observations (rows) $10$ through $15$.

In [13]:
df.loc[10:15, ['TAG', 'Smoke']]

    TAG  Smoke
10  1.7      0
11  2.0      0
12  2.3      0
13  2.1      0
14  2.4      0
15  2.6      2

### Task 3: The `to_list` method creates a Python list object. Use the `to_list` method to create a Python list object of the `Age` values for those that have a value in the `HR` (heart rate) column that is more than $72$. Print only the first $10$ values.

In [19]:
df.loc[df.HR > 72, 'Age'].to_list()[:10]

[57, 52, 49, 70, 45, 53, 50, 33, 30, 44]

### Task 4: Create a variable named `selection` that will select for all the observations who never smoked, as a heart rate, `HR`, less than $80$, and a systolic blood pressure, `sBP`, of less than $120$. Use this selection to create a numpy $n$-dimensional array of the `Age` and `triacylglycerol`, `TAG`, variable values.

In [21]:
selection = (df.Smoke == 0) & (df.HR < 80) & (df.sBP < 120)
df.loc[selection, ['Age', 'TAG']].to_numpy

<bound method DataFrame.to_numpy of     Age  TAG
1    53  0.6
3    43  1.6
8    44  2.4
11   35  2.0
21   45  2.1
41   55  3.1>

### Task 5: Create a new variable named `AgeHR` that is the product of the values in the variables `Age` and `HR`.

In [24]:
df['AgeHR'] = df.Age * df.HR
df['AgeHR']

0      2021
1      2703
2      1782
3      2322
4      2806
       ...
195    6336
196    5022
197    6039
198    6370
199    6732
Name: AgeHR, Length: 200, dtype: int64

### Task 6: Create a new variable in the dataframe called `HRLevel` from the `HR` column with intervals  $(0,65]$,$(65,78]$,$(78,1000)$ with labels `low`, `normal`, and `high` respectively.

In [29]:
df['HRLevel'] = pd.cut(df.HR, bins = [0, 65, 78, 1000], right=True, labels=['low', 'normal', 'high'])
df.HRLevel[:5]

0    low
1    low
2    low
3    low
4    low
Name: HRLevel, dtype: category
Categories (3, object): ['low' < 'normal' < 'high']

## Questions

### Question 1: How do you import the pandas library in Python?

See below. The `as pd` part is not required for importing pandas, though it makes working with it easier.

In [1]:
import pandas as pd

### Question 2: How do you read a CSV file named `data.csv` into a pandas DataFrame?

Use `df = pd.read_csv('data.csv')`. I have commnted this out below and imported the file using the raw method, so I actually have data to work with since I do not have the file downloaded and located in this repo.

In [2]:
# df = pd.read_csv('data.csv')
df = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/PUBH1142Chap0801.csv')

### Question 3: How do you display the first $5$ rows of a DataFrame named `df`?

`df.head()` displays the first $5$ rows by default.

In [3]:
df.head()

,Name,DOB,Age,Vocation,Smoke,HR,sBP,CholesterolBefore,TAG,Survey,CholesterolAfter,Delta,Group
0,Dylan Patton,1981-10-07,43,Energy manager,0,47,145,1.2,1.2,1,0.7,0.5,Active
1,Sandra Howard,1993-01-27,53,Tax adviser,0,51,115,1.2,0.6,3,1.0,0.2,Active
2,Samantha Williams,1973-12-21,33,IT consultant,0,54,120,2.0,1.3,3,1.7,0.3,Active
3,Ashley Hensley,1981-12-01,43,"Nurse, children's",0,54,103,2.1,1.6,4,2.1,0.0,Active
4,Robert Wilson,1964-06-23,46,Clinical embryologist,0,61,138,2.8,2.1,5,2.8,0.0,Active

### Question 4: How do you find the number of rows and columns in a DataFrame `df`?

The `shape` attribute shows use the number of rows and columns, returned as a tuple.

In [4]:
df.shape

(200, 13)

### Question 5: How do you print the names of all the columns in a DataFrame `df`?

The columns attribute lists all the column header names, called labels.

In [46]:
df.columns

Index(['Patient', 'DOB', 'Age', 'Vocation', 'Smoke', 'HR', 'sBP',
       'CholesterolBefore', 'TAG', 'Survey', 'CholesterolAfter', 'Delta',
       'Group', 'AgeHR', 'C', 'HRLevel'],
      dtype='object')

### Question 6: How do you get the summary information of the DataFrame `df` including data types and non-null values?

The `info()` function returns the summary information including the Python data type of the values in each of the columns and count of non-null values in each column.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               200 non-null    object
 1   DOB                200 non-null    object
 2   Age                200 non-null    int64
 3   Vocation           200 non-null    object
 4   Smoke              200 non-null    int64
 5   HR                 200 non-null    int64
 6   sBP                200 non-null    int64
 7   CholesterolBefore  200 non-null    float64
 8   TAG                200 non-null    float64
 9   Survey             200 non-null    int64
 10  CholesterolAfter   200 non-null    float64
 11  Delta              200 non-null    float64
 12  Group              200 non-null    object
dtypes: float64(4), int64(5), object(4)
memory usage: 20.4+ KB

### Question 7: How do you select only the rows in DataFrame `df` where the column `A` is greater than $5$?

See below. I have commented out the answer using the column name `A` and have left other code uncommented so I can work with the dataset I read in.

In [47]:
# df[df.A > 5]
df[df.Age > 5]

,Patient,DOB,Age,Vocation,Smoke,HR,sBP,CholesterolBefore,TAG,Survey,CholesterolAfter,Delta,Group,AgeHR,C,HRLevel
0,Dylan Patton,1981-10-07,43,Energy manager,0,47,145,1.2,1.2,1,0.7,0.5,Active,2021,90,low
1,Sandra Howard,1993-01-27,53,Tax adviser,0,51,115,1.2,0.6,3,1.0,0.2,Active,2703,104,low
2,Samantha Williams,1973-12-21,33,IT consultant,0,54,120,2.0,1.3,3,1.7,0.3,Active,1782,87,low
3,Ashley Hensley,1981-12-01,43,"Nurse, children's",0,54,103,2.1,1.6,4,2.1,0.0,Active,2322,97,low
4,Robert Wilson,1964-06-23,46,Clinical embryologist,0,61,138,2.8,2.1,5,2.8,0.0,Active,2806,107,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,John Curtis,1936-11-25,66,"Sales professional, IT",1,96,201,10.1,5.1,5,10.0,0.1,Control,6336,162,high
196,Jessica Tanner,1986-07-01,54,Paramedic,1,93,183,10.1,5.3,5,10.0,0.1,Control,5022,147,high
197,Charles Smith,1959-01-30,61,Chartered certified accountant,0,99,212,10.1,5.6,4,9.7,0.4,Control,6039,160,high
198,Barry Porter,1979-05-30,65,Dancer,1,98,200,10.1,5.3,3,10.0,0.1,Control,6370,163,high
199,Julie Barrett,1972-07-27,66,Theme park manager,1,102,208,11.1,5.7,2,10.7,0.4,Active,6732,168,high

### Question 8: How do you select the columns `A` and `B` from the DataFrame `df`?

The `loc` property can be used to locate columns by their names (as a list or a slice).
I have commented out the answer using the column names `A` and `B` and have left other code uncommented so I can work with the dataset I read in.

In [15]:
# df.loc[:, ['A', 'B']]
df.loc[:, ['Name', 'Age']]

                  Name  Age
0         Dylan Patton   43
1        Sandra Howard   53
2    Samantha Williams   33
3       Ashley Hensley   43
4        Robert Wilson   46
..                 ...  ...
195        John Curtis   66
196     Jessica Tanner   54
197      Charles Smith   61
198       Barry Porter   65
199      Julie Barrett   66

[200 rows x 2 columns]

### Question 9: How do you rename the column `A` to `Alpha` in DataFrame `df`?

Use the rename method with `inplace=True`. 
See below. I have commented out the answer using the column name `A` and have left other code uncommented so I can work with the dataset I read in.

In [ ]:
# df.rename(columns={'A': 'Alpha'}, inplace=True)
# df.columns # Call the column names
df.rename(columns={'Name': 'Patient'}, inplace=True)
df.columns # Call the column names

Index(['Patient', 'DOB', 'Age', 'Vocation', 'Smoke', 'HR', 'sBP',
       'CholesterolBefore', 'TAG', 'Survey', 'CholesterolAfter', 'Delta',
       'Group'],
      dtype='object')

### Question 10: How do you replace all occurrences of the value $999$ in DataFrame `df` with `nan`?

The `na_values` argument can take a Python list object that contains all the default values that indicate missing values. I am now using a new csv file that contains missing data whith the value $999$ representing nan to demonstrate this.

In [39]:
default_missing_df = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/DefaultMissingData.csv', na_values=[999])
default_missing_df

     age salary previous_company
0   57.0    Nil                1
1   56.0  50927          Missing
2   46.0  75500                3
3    NaN  84417          Missing
4   60.0  63002                1
5   54.0  54652          Missing
6    NaN  65739                1
7   64.0  89397                3
8   60.0  77797                4
9   61.0    Nil                1
10  51.0  92767                5
11   NaN  59873                2
12  49.0  91001                4
13  59.0  54212                4
14  61.0  84423                2
15   NaN    Nil                3
16  61.0  84930          Missing
17  48.0  63824                5
18  53.0  53143                2
19  49.0  59842          Missing
20  55.0  79309                2
21  59.0    Nil                4
22  49.0  52895                1
23  57.0  54035                3
24  58.0  64962                3
25  61.0    Nil                1
26  63.0  63861                2
27  47.0  55188                3
28  63.0  61220                3
29  54.0  98314          Missing
30  49.0  63398                1
31  57.0  94900                5

In [40]:
# The following code also converts Nil and Missinsg to NaN
default_missing_df = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/DefaultMissingData.csv', na_values=[999, 'Nil', 'Missing'])
default_missing_df

     age   salary  previous_company
0   57.0      NaN               1.0
1   56.0  50927.0               NaN
2   46.0  75500.0               3.0
3    NaN  84417.0               NaN
4   60.0  63002.0               1.0
5   54.0  54652.0               NaN
6    NaN  65739.0               1.0
7   64.0  89397.0               3.0
8   60.0  77797.0               4.0
9   61.0      NaN               1.0
10  51.0  92767.0               5.0
11   NaN  59873.0               2.0
12  49.0  91001.0               4.0
13  59.0  54212.0               4.0
14  61.0  84423.0               2.0
15   NaN      NaN               3.0
16  61.0  84930.0               NaN
17  48.0  63824.0               5.0
18  53.0  53143.0               2.0
19  49.0  59842.0               NaN
20  55.0  79309.0               2.0
21  59.0      NaN               4.0
22  49.0  52895.0               1.0
23  57.0  54035.0               3.0
24  58.0  64962.0               3.0
25  61.0      NaN               1.0
26  63.0  63861.0               2.0
27  47.0  55188.0               3.0
28  63.0  61220.0               3.0
29  54.0  98314.0               NaN
30  49.0  63398.0               1.0
31  57.0  94900.0               5.0

### Question 11: How do you drop all rows in DataFrame `df` that contain missing values?

The `dropna` method deletes all rows that contain missing data for any of the columns in that row. All the data for that row (observation) are lost. The removal is not permanent. Below, the dataframe with dropped rows is reassigned to a new variable, leaving the original intact. I am now using a new csv file that contains missing data to demonstrate this.

In [42]:
# Read the MissingData.csv file and assign it to the variable df_missing this contains missing values
df_missing = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/MissingData.csv')
df_missing.head()

    age   salary  previouscompany
0  57.0      NaN              1.0
1  56.0  50927.0              NaN
2  46.0  75500.0              3.0
3   NaN  84417.0              NaN
4  60.0  63002.0              1.0

In [43]:
# Delete rows with missing values and assign to a new variable complete_data_df
complete_data_df = df_missing.dropna()
complete_data_df

     age   salary  previouscompany
2   46.0  75500.0              3.0
4   60.0  63002.0              1.0
7   64.0  89397.0              3.0
8   60.0  77797.0              4.0
10  51.0  92767.0              5.0
12  49.0  91001.0              4.0
13  59.0  54212.0              4.0
14  61.0  84423.0              2.0
17  48.0  63824.0              5.0
18  53.0  53143.0              2.0
20  55.0  79309.0              2.0
22  49.0  52895.0              1.0
23  57.0  54035.0              3.0
24  58.0  64962.0              3.0
26  63.0  63861.0              2.0
27  47.0  55188.0              3.0
28  63.0  61220.0              3.0
30  49.0  63398.0              1.0
31  57.0  94900.0              5.0

### Question 12: How do you fill all missing values in DataFrame `df` with $0$?

Use the `fillna` method. See Below.

In [44]:
df_missing.fillna(0, inplace=True)
df_missing

     age   salary  previouscompany
0   57.0      0.0              1.0
1   56.0  50927.0              0.0
2   46.0  75500.0              3.0
3    0.0  84417.0              0.0
4   60.0  63002.0              1.0
5   54.0  54652.0              0.0
6    0.0  65739.0              1.0
7   64.0  89397.0              3.0
8   60.0  77797.0              4.0
9   61.0      0.0              1.0
10  51.0  92767.0              5.0
11   0.0  59873.0              2.0
12  49.0  91001.0              4.0
13  59.0  54212.0              4.0
14  61.0  84423.0              2.0
15   0.0      0.0              3.0
16  61.0  84930.0              0.0
17  48.0  63824.0              5.0
18  53.0  53143.0              2.0
19  49.0  59842.0              0.0
20  55.0  79309.0              2.0
21  59.0      0.0              4.0
22  49.0  52895.0              1.0
23  57.0  54035.0              3.0
24  58.0  64962.0              3.0
25  61.0      0.0              1.0
26  63.0  63861.0              2.0
27  47.0  55188.0              3.0
28  63.0  61220.0              3.0
29  54.0  98314.0              0.0
30  49.0  63398.0              1.0
31  57.0  94900.0              5.0

### Question 13: How do you calculate the mean of column `A` in DataFrame `df`?

See below. I have commented out the answer using the column name `A` and have left other code uncommented so I can work with the dataset I read in.

In [ ]:
# a_col = df['A'].to_numpy()
# a_col.mean()
age = df['Age'].to_numpy()
age.mean()

np.float64(53.07)

### Question 14: How do you create a new column `C` in DataFrame `df` that is the sum of columns `A` and `B`?

See below. I have commented out the answer using the column names `A` and `B` and have left other code uncommented so I can work with the dataset I read in.

In [28]:
# df['C'] = df.A + df.B
df['C'] = df.Age + df.HR
df['C']

0       90
1      104
2       87
3       97
4      107
      ...
195    162
196    147
197    160
198    163
199    168
Name: C, Length: 200, dtype: int64

### Question 15: How do you save the DataFrame `df` to a CSV file named `output.csv`? (Find the solution by searching the pandas documentation.)

Use the `to_csv` method. Optionally, set `index=False` to prevent the index/row numbers of the DataFrame from being included as the first column in the csv (the default is `index=True`.). See below.

In [45]:
df.to_csv('output.csv', index=False)